# CONFIGURACIÓN DE BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3309/bd_punamba_market?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=05frank*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIÓN JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# AJUSTES DE SESIÓN Y CARGA (Para evitar Error 500 en relaciones)
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# CONFIGURACIÓN DEL SERVIDOR
server.port=8090

# --- CONFIGURACIÓN DE SEGURIDAD JWT ---

# Clave secreta para firmar los tokens (Cámbiala por algo más complejo en producción)
# Debe tener al menos 32 caracteres para ser segura con HS256
jwt.secret=70756e616d62615f6d61726b6574706c6163655f7365637265745f6b65795f32303236

# Access Token: 15 minutos (900000 ms)
jwt.expiration=900000

# Refresh Token: 7 días (604800000 ms)
jwt.refresh-expiration=604800000

# SUBIDA DE ARCHIVOS
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# opcional para tomcat
server.tomcat.max-swallow-size=20MB